### ISSUE TITLE
Database Schema for Event

### ISSUE THREAD

**Issue by devppratik** [Developer-Student-Clubs-VSSUT-Burla/CEM-backend#10]
A DB schema/ mdoel needs to designed to store the details of the events. It should include information such as - 

- Name
- Date
- Type (Offline/ Online)
- Registration Fees
- Expected Attendees
- Created by
- Created on 

Also the user schema needs to be updated so as to include the ids of events created by user

**Tasks** 
- [ ] Create Model for Events
- [ ] Update User Model

**Comment by Pallav-19** [comment]
Please assign it to me.

**Comment by chandrasekhar2039** [comment]
> Any defaults to be set at any fields??

Major fields such as `Name`, `Date`, `Type`, `Registration Fees`, `Expected Attendees` must be marked as required. Other than this, fields like `Created by` should by default populate the **name of the organizer conducting the event** and `Created on` should by default take the exact time when this event is being created in UTC format.
