### ISSUE TITLE
API Routes for Managing Events

### ISSUE THREAD

**Issue by devppratik** [Developer-Student-Clubs-VSSUT-Burla/CEM-backend#12]
Routes and their Controller Logic needs to be added for the following specifications

- [ ] Deleting Events
- [ ] Get List of All Past Events
- [ ] Get Stats for Each Event(Total Registration, Total Fees etc)
- [ ] Managing Event Attendees and Tickets

**Comment by alphaCoderR** [comment]
Can I work on this issue??
